name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-chromadb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku Container Registry
        run: |
          heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Pull ChromaDB image
        run: docker pull chromadb/chroma:0.5.3

      - name: Check if Heroku app exists
        id: check_db_app
        run: |
          if heroku apps:info $HEROKU_DB_APP_NAME > /dev/null 2>&1; then
              echo "App exists"
              echo "::set-output name=exists::true"
          else
              echo "App does not exist"
              echo "::set-output name=exists::false"
          fi
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DB_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Create Heroku app
        if: steps.check_db_app.outputs.exists == 'false'
        run: heroku create $HEROKU_DB_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DB_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Tag and push to Heroku
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DB_APP_NAME }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker tag chromadb/chroma:0.5.3 registry.heroku.com/$HEROKU_DB_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_DB_APP_NAME/web

      - name: Set environment variables
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DB_APP_NAME }}
          CHROMA_SERVER_HOST: 0.0.0.0
          CHROMA_SERVER_PORT: 8000
          CHROMA_SERVER_AUTHN_PROVIDER: chromadb.auth.token_authn.TokenAuthenticationServerProvider
          CHROMA_SERVER_AUTHN_CREDENTIALS: ${{ secrets.CHROMA_AUTH_TOKEN }}
        run: |
          heroku config:set CHROMA_SERVER_HOST=$CHROMA_SERVER_HOST --app $HEROKU_DB_APP_NAME
          heroku config:set CHROMA_SERVER_PORT=$CHROMA_SERVER_PORT --app $HEROKU_DB_APP_NAME
          heroku config:set CHROMA_SERVER_AUTHN_PROVIDER=$CHROMA_SERVER_AUTHN_PROVIDER --app $HEROKU_DB_APP_NAME
          heroku config:set CHROMA_SERVER_AUTHN_CREDENTIALS=$CHROMA_SERVER_AUTHN_CREDENTIALS --app $HEROKU_DB_APP_NAME

      - name: Release the app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_DB_APP_NAME }}
        run: heroku container:release web --app $HEROKU_DB_APP_NAME
